version: "3.9"
services:
  jinaga-test:
    image: jinaga-test
    depends_on:
      db:
        condition: service_healthy
    links:
    - postgres
  db:
    image: jinaga-postgres-fact-keystore
    environment:
    - POSTGRES_PASSWORD=superuser
    - APP_USERNAME=dev
    - APP_PASSWORD=devpw
    - APP_DATABASE=integrationtest
    ports:
    - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5